apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-feedback-deploy
  namespace: ai-feedback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-feedback
  template:
    metadata:
      labels:
        app: ai-feedback
    spec:
      containers:
        - name: api
          image: your-dockerhub/ai-feedback:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            # Uncomment when using real DB
            # - secretRef:
            #     name: db-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

